export const PRODUCT_LIST_REQUEST ='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS ='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE ='PRODUCT_LIST_FAILURE'

export const UPDATE_PRODUCT_REQUEST ='UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS ='UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE ='UPDATE_PRODUCT_FAILURE'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';